import type { Metadata } from 'next'
import { Inter, Lora } from 'next/font/google'
import Nav from './nav'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const lora = Lora({ subsets: ['latin'] }) // TODO: try some other options https://fonts.google.com/?stroke=Serif&vfonly=true&preview.text=Tally

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={lora.className}>Tally 🏁</header>
        <Nav />
        {children}
      </body>
    </html>
  )
}
