export const colors = {
    light: {
        transparent: 'transparent',
        text: '#33333f',
        background: '#fff',
        tileBackground: '#fff',
        tileBorder: '#000',
        navBackground: '#fafaff',
        buttonBorder: '#000',
        link: '#3868D6',
        boxShadow: '#000',
        selectTrack: '#eaeaef',
        selectIndicator: '#efeffa',
    },
    dark: {
        transparent: 'transparent',
        text: '#eaeaef',
        background: '#1a1a1f',
        tileBackground: '#21212f',
        tileBorder: '#000',
        navBackground: '#12121f',
        buttonBorder: '#777',
        link: '#3f73ed',
        boxShadow: '#000',
        selectTrack: '#10101f',
        selectIndicator: '#22222f',
    },
}